### ISSUE TITLE
fizzbuzz with if, for

### ISSUE THREAD

**Issue by jinsoooo49** [jinsoooo49/fizzbuzz-py#1]
# Description

## Tasks

- [ ] For statement(range: 1 to 15)
- [ ] Print 'fizz' if i times of 3
- [ ] Print 'buzz' if i times of 5
- [ ] Print 'fizzbuzz' if i is times of 15
